### PR TITLE
Child Health updates - 7th October

### PR DESCRIPTION
**Pull request by lucindalawrie**
- Updated files and dates
- Formatted chart colours
- Updated commentary

(Made changes to some other file paths - deaths and immunisation - so that I could run the app but these might cause some merge conflicts so can be reverted if necessary) 

Thanks 😃

### CODE REVIEW

**Review by jvillacampa — APPROVED** [review]
Looks good. I think in future updates we need to look at the visualisations as they are becoming increasingly difficult to read with so many lines there. For example, weekly data might not be that relevant anymore and we might want to aggregate some months together

**Comment by lucindalawrie** [comment]
I agree, the chart is getting very busy and with the move to updating the dashboard monthly I think it would make sense that the data is aggregated by month too. I can raise this with Susanne and see what she thinks?

**Comment by jvillacampa** [comment]
Yes, that would be good. It happends in the immunisation one as well, so we could include them in the conversation as well

**Comment by lucindalawrie** [comment]
Remind me again, is it Judith that does the immunisation data?

**Comment by vaelliott** [comment]
yes judith or salomi

**Pull request merged**
